#!/bin/bash

USAGE_STR="usage: $0 [repo_path] [project_name]\n\
Don't use it before commit all you need, or file may be deleted!"

if [ "$#" -ne 2 ]; then
	echo -e $USAGE_STR
	exit
fi

export REPO_PATH=$(cd "$1" && pwd -P)

if [ ! -d "$REPO_PATH" ]; then
	echo "can not find dir $1"
	echo -e $USAGE_STR
	exit
fi

export TIMEOUT=5
export SHELL_PATH=$(dirname $(realpath "$0"))
export LIB_PATH="$SHELL_PATH/lib"
export INCLUDE_PATH="$SHELL_PATH/include"
export STUB_PATH="$SHELL_PATH/${2,,}"

if [ ! -d "$STUB_PATH" ]; then
	echo "can not find exam $2"
	echo -e $USAGE_STR
	exit
fi

if [ ! -f "$SHELL_PATH/.env" ]; then
	echo "$SHELL_PATH/.env"
	cat <<- EOF > "$SHELL_PATH/.env"
	SHELL_PATH=$SHELL_PATH
	INCLUDE_PATH=$INCLUDE_PATH
	LIB_PATH=$LIB_PATH
	STUB_PATH=$STUB_PATH
	EOF

fi

clean() {
	echo ""
	echo -n "Clean: "
	$(cd "$REPO_PATH" && git clean -qfd) && echo "done" 
}
trap clean EXIT SIGINT SIGTERM

NORM_OPT=()
if [ -f "$STUB_PATH/env" ]; then
	source "$STUB_PATH/env"
fi
echo ""
echo "Norminette: "
norminette $NORM_OPT "$REPO_PATH" || exit

OUTPUT_DIR="./$(basename "$REPO_PATH")-outputs"
mkdir $OUTPUT_DIR
for EXAM_NAME in $(cd "$STUB_PATH" && ls -d */); do
	echo ""
	echo -n "[$EXAM_NAME] compile: "
	(EXAM_DIR="$EXAM_NAME" "$SHELL_PATH/cmd/compile_exam.sh" && echo "done") || continue
	echo -n "[$EXAM_NAME] run: "
	(EXAM_DIR="$EXAM_NAME" "$SHELL_PATH/cmd/execute_exam.sh" && echo "done") || continue
	echo -n "[$EXAM_NAME] test: "
	(EXAM_DIR="$EXAM_NAME" "$SHELL_PATH/cmd/test_exam.sh" && echo "done") || continue

	echo "Success"
done

for EXAM_NAME in $(cd "$STUB_PATH" && ls -d */); do
	cp "$REPO_PATH/$EXAM_NAME/output" "$OUTPUT_DIR/$(basename $EXAM_NAME).output"
	cp "$REPO_PATH/$EXAM_NAME/app" "$OUTPUT_DIR/$(basename $EXAM_NAME).app"
	if [ -s "$REPO_PATH/$EXAM_NAME/errlog" ]; then
		cp "$REPO_PATH/$EXAM_NAME/errlog" "$OUTPUT_DIR/$(basename $EXAM_NAME).errlog"
	fi
done
